# Generated by Django 4.2.3 on 2023-07-22 04:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(blank=None, default=datetime.date.today, null=None)),
                ('UltimaFecha', models.DateField(blank=None, default=datetime.date.today, null=None)),
                ('Boton1', models.BigIntegerField()),
                ('Boton2', models.BigIntegerField()),
                ('Usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='Usuarios.usuarios')),
            ],
        ),
    ]
