# Generated by Django 4.2.3 on 2023-07-22 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Usuarios.usuarios'),
        ),
    ]
