# Generated by Django 4.2.3 on 2023-07-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_alter_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='UltimaFecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
