# Generated by Django 4.2.3 on 2023-07-22 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CC', 'Cedula Ciudadania'), ('TI', 'Tajeta de identidad')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('1', 'Regular'), ('2', 'Admin')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.TextField(max_length=50)),
                ('Correo', models.TextField(default='', max_length=50)),
                ('dni', models.BigIntegerField()),
                ('Password', models.CharField(default='', max_length=128)),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Usuarios.tipo')),
                ('Usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
