# Generated by Django 4.2.3 on 2023-07-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuarios_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Correo',
            field=models.TextField(default='', max_length=50),
        ),
    ]
