# Generated by Django 4.2.3 on 2023-07-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuarios_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
